create table USERS (
   ID INT NOT NULL AUTO_INCREMENT,    
   NAME VARCHAR(20) NOT NULL,
   PWD  VARCHAR(500) NOT NULL,
   PRIMARY KEY PK_USERS(ID)	 
);

create table SHOP (
   ID INT NOT NULL AUTO_INCREMENT,
   NAME VARCHAR(500) NOT NULL,
   SHORT_NAME VARCHAR(100) NOT NULL,
   CREATED_AT TIMESTAMP NOT NULL,
   CREATED_BY INT NOT NULL,
   UPDATED_AT TIMESTAMP NOT NULL,
   UPDATED_BY INT NOT NULL,
   IS_DELETED BOOLEAN,
   PRIMARY KEY PK_SHOP(ID),
   CONSTRAINT FOREIGN KEY FK_USER_SHOP_CREATED(CREATED_BY)  
       REFERENCES USERS (ID),
   CONSTRAINT FOREIGN KEY FK_USER_SHOP_UPDATED(UPDATED_BY)  
       REFERENCES USERS (ID)    
);


create table CATEGORY (
   ID INT NOT NULL AUTO_INCREMENT,
   SHOP_ID INT NOT NULL,
   NAME VARCHAR(200) NOT NULL,
   CREATED_AT TIMESTAMP NOT NULL,
   CREATED_BY INT NOT NULL,
   UPDATED_AT TIMESTAMP NOT NULL,
   UPDATED_BY INT NOT NULL,
   IS_DELETED BOOLEAN,
   PRIMARY KEY PK_CAT (ID),
   CONSTRAINT FOREIGN KEY FK_SHOP_CATEGORY (SHOP_ID)  
       REFERENCES SHOP (ID) 
       ON DELETE CASCADE
       ON UPDATE NO ACTION,
   CONSTRAINT FOREIGN KEY FK_USER_CAT_CREATED(CREATED_BY)  
       REFERENCES USERS (ID),
   CONSTRAINT FOREIGN KEY FK_USER_CAT_UPDATED(UPDATED_BY)  
       REFERENCES USERS (ID)
);

create table PRODUCT (
   ID INT NOT NULL AUTO_INCREMENT,
   CAT_ID INT NOT NULL,
   ITEMID INT NOT NULL AUTO_INCREMENT,
   NAME VARCHAR(200) NOT NULL DEFAULT '',
   IMAGEURL VARCHAR(500) DEFAULT '',
   PRICE DECIMAL(10, 2) DEFAULT 0,
   CREATED_AT TIMESTAMP NOT NULL,
   CREATED_BY INT NOT NULL,
   UPDATED_AT TIMESTAMP NOT NULL,
   UPDATED_BY INT NOT NULL,
   IS_DELETED BOOLEAN,
   PRIMARY KEY PK_PRODUCT (ID),
   CONSTRAINT FOREIGN KEY FK_CATEGORY_PRODUCT (CAT_ID)  
       REFERENCES CATEGORY (ID) 
       ON DELETE CASCADE
       ON UPDATE NO ACTION,
   CONSTRAINT FOREIGN KEY FK_USER_PROD_CREATED(CREATED_BY)  
       REFERENCES USERS (ID),
   CONSTRAINT FOREIGN KEY FK_USER_PROD_UPDATED(UPDATED_BY)  
       REFERENCES USERS (ID)
);


