DROP TABLE PRODUCT;
DROP TABLE CATEGORY;
DROP TABLE SHOP;
DROP TABLE NEWS;
DROP TABLE USERS;

create table SHOP (
   ID INT NOT NULL AUTO_INCREMENT,
   NAME VARCHAR(300) NOT NULL,
   SHORT_NAME VARCHAR(100) NOT NULL,
   CREATED_AT TIMESTAMP NOT NULL,
   UPDATED_AT TIMESTAMP NOT NULL,
   IS_DELETED BOOLEAN DEFAULT false
);

create table USERS (
   ID INT NOT NULL AUTO_INCREMENT,    
   SHOP_ID INT NOT NULL,
   NAME VARCHAR(20) NOT NULL,
   PWD  VARCHAR(30) NOT NULL,
   FIRSTNAME VARCHAR(100) NOT NULL DEFAULT ''
   LASTNAME VARCHAR(100) NOT NULL DEFAULT ''
   PRIMARY KEY PK_USERS(ID), 
   CONSTRAINT FOREIGN KEY FK_USERS_SHOP (SHOP_ID) REFERENCES SHOP (ID)
);
alter table USERS ADD UNIQUE IDX_USER_SHOP (SHOP_ID, NAME);

create table CATEGORY (
   ID INT NOT NULL AUTO_INCREMENT,
   SHOP_ID INT NOT NULL,
   NAME VARCHAR(200) NOT NULL,
   CREATED_AT TIMESTAMP NOT NULL,
   CREATED_BY INT NOT NULL,
   UPDATED_AT TIMESTAMP NOT NULL,
   UPDATED_BY INT NOT NULL,
   IS_DELETED BOOLEAN DEFAULT false,
   PRIMARY KEY PK_CAT (ID),
   CONSTRAINT FOREIGN KEY FK_SHOP_CATEGORY (SHOP_ID)  
       REFERENCES SHOP (ID) 
       ON DELETE CASCADE
       ON UPDATE NO ACTION,
   CONSTRAINT FOREIGN KEY FK_USER_CAT_CREATED(CREATED_BY)  
       REFERENCES USERS (ID),
   CONSTRAINT FOREIGN KEY FK_USER_CAT_UPDATED(UPDATED_BY)  
       REFERENCES USERS (ID)
);
ALTER TABLE CATEGORY ADD UNIQUE IDX_CATEGORY_SHOP (SHOP_ID, NAME);

create table PRODUCT (
   ID INT NOT NULL AUTO_INCREMENT,
   CAT_ID INT NOT NULL,
   NAME VARCHAR(4000) NOT NULL DEFAULT '',
   DESCRIPTION VARCHAR(4000) DEFAULT '',
   IMAGEURL VARCHAR(1000) DEFAULT '',
   PRICE DECIMAL(10, 2) DEFAULT 0,
   CREATED_AT TIMESTAMP NOT NULL,
   CREATED_BY INT NOT NULL,
   UPDATED_AT TIMESTAMP NOT NULL,
   UPDATED_BY INT NOT NULL,
   IS_DELETED BOOLEAN DEFAULT false,
   PRIMARY KEY PK_PRODUCT (ID),
   CONSTRAINT FOREIGN KEY FK_CATEGORY_PRODUCT (CAT_ID)  
       REFERENCES CATEGORY (ID) 
       ON DELETE CASCADE
       ON UPDATE NO ACTION,
   CONSTRAINT FOREIGN KEY FK_USER_PROD_CREATED(CREATED_BY)  
       REFERENCES USERS (ID),
   CONSTRAINT FOREIGN KEY FK_USER_PROD_UPDATED(UPDATED_BY)  
       REFERENCES USERS (ID)
);


CREATE TABLE NEWS (
   ID int NOT NULL auto_increment,
   SHOP_ID INT NOT NULL,
   CONTENTS	varchar(4000) NOT NULL DEFAULT '',
   CREATED_AT TIMESTAMP NOT NULL,
   CREATED_BY INT NOT NULL,
   UPDATED_AT TIMESTAMP NOT NULL,
   UPDATED_BY INT NOT NULL,
   IS_DELETED BOOLEAN DEFAULT 0,
   PRIMARY KEY PK_NEWS (ID),
   CONSTRAINT FOREIGN KEY FK_SHOP_NEWS (SHOP_ID)  
       REFERENCES SHOP (ID) 
       ON DELETE CASCADE
       ON UPDATE NO ACTION,
   CONSTRAINT FOREIGN KEY FK_USER_NEWS_CREATED(CREATED_BY)  
       REFERENCES USERS (ID),
   CONSTRAINT FOREIGN KEY FK_USER_NEWS_UPDATED(UPDATED_BY)  
       REFERENCES USERS (ID)
);

