
set names utf8; 

insert into ALBUMCATEGORY(NAME, CREATEDAT, COLSEQ)
   VALUES ('小冊子', CURRENT_TIMESTAMP(), 1);

insert into ALBUMCATEGORY(NAME, CREATEDAT, COLSEQ)
   VALUES ('窩打老道', CURRENT_TIMESTAMP(), 2);

insert into ALBUMCATEGORY(NAME, CREATEDAT, COLSEQ)
   VALUES ('美術室', CURRENT_TIMESTAMP(), 3);

insert into ALBUMCATEGORY(NAME, CREATEDAT, COLSEQ)
   VALUES ('課室', CURRENT_TIMESTAMP(), 4);

insert into ALBUMCATEGORY(NAME, CREATEDAT, COLSEQ)
   VALUES ('庭院', CURRENT_TIMESTAMP(), 5);

insert into ALBUMCATEGORY(NAME, CREATEDAT, COLSEQ)
   VALUES ('舊翼', CURRENT_TIMESTAMP(), 6);

insert into ALBUMCATEGORY(NAME, CREATEDAT, COLSEQ)
   VALUES ('修道院', CURRENT_TIMESTAMP(), 7);

insert into ALBUMCATEGORY(NAME, CREATEDAT, COLSEQ)
   VALUES ('體育設施', CURRENT_TIMESTAMP(), 8);

INSERT INTO ALBUMIMAGE (CATEGORY_ID, URL, COLSEQ) 
  VALUES ((SELECT ID FROM ALBUMCATEGORY WHERE NAME = '小冊子'), 'images/leaflet0.jpg', 1);

INSERT INTO ALBUMIMAGE (CATEGORY_ID, URL, COLSEQ) 
  VALUES ((SELECT ID FROM ALBUMCATEGORY WHERE NAME = '小冊子'), 'images/leaflet1.jpg', 2);

INSERT INTO ALBUMIMAGE (CATEGORY_ID, URL, COLSEQ) 
  VALUES ((SELECT ID FROM ALBUMCATEGORY WHERE NAME = '小冊子'), 'images/leaflet2.jpg', 3);

INSERT INTO ALBUMIMAGE (CATEGORY_ID, URL, COLSEQ) 
  VALUES ((SELECT ID FROM ALBUMCATEGORY WHERE NAME = '小冊子'), 'images/leaflet3.jpg', 4);

INSERT INTO ALBUMIMAGE (CATEGORY_ID, URL, COLSEQ) 
  VALUES ((SELECT ID FROM ALBUMCATEGORY WHERE NAME = '窩打老道'), 'images/outside_banner.jpg', 1);

INSERT INTO ALBUMIMAGE (CATEGORY_ID, URL, COLSEQ) 
  VALUES ((SELECT ID FROM ALBUMCATEGORY WHERE NAME = '窩打老道'), 'images/outside0.jpg', 2);

INSERT INTO ALBUMIMAGE (CATEGORY_ID, URL, COLSEQ) 
  VALUES ((SELECT ID FROM ALBUMCATEGORY WHERE NAME = '窩打老道'), 'images/outside1.jpg', 3);

INSERT INTO ALBUMIMAGE (CATEGORY_ID, URL, COLSEQ) 
  VALUES ((SELECT ID FROM ALBUMCATEGORY WHERE NAME = '窩打老道'), 'images/outside2.jpg', 4);

INSERT INTO ALBUMIMAGE (CATEGORY_ID, URL, COLSEQ) 
  VALUES ((SELECT ID FROM ALBUMCATEGORY WHERE NAME = '窩打老道'), 'images/outside3.jpg', 5);

INSERT INTO ALBUMIMAGE (CATEGORY_ID, URL, COLSEQ) 
  VALUES ((SELECT ID FROM ALBUMCATEGORY WHERE NAME = '窩打老道'), 'images/outside4.jpg', 6);

INSERT INTO ALBUMIMAGE (CATEGORY_ID, URL, COLSEQ) 
  VALUES ((SELECT ID FROM ALBUMCATEGORY WHERE NAME = '美術室'), 'images/artroom1.jpg', 1);

INSERT INTO ALBUMIMAGE (CATEGORY_ID, URL, COLSEQ) 
  VALUES ((SELECT ID FROM ALBUMCATEGORY WHERE NAME = '美術室'), 'images/artroom2.jpg', 2);

INSERT INTO ALBUMIMAGE (CATEGORY_ID, URL, COLSEQ) 
  VALUES ((SELECT ID FROM ALBUMCATEGORY WHERE NAME = '美術室'), 'images/artroom3.jpg', 3);

INSERT INTO ALBUMIMAGE (CATEGORY_ID, URL, COLSEQ) 
  VALUES ((SELECT ID FROM ALBUMCATEGORY WHERE NAME = '美術室'), 'images/artroom4.jpg', 4);

INSERT INTO ALBUMIMAGE (CATEGORY_ID, URL, COLSEQ) 
  VALUES ((SELECT ID FROM ALBUMCATEGORY WHERE NAME = '課室'), 'images/classroom1.jpg', 1);

INSERT INTO ALBUMIMAGE (CATEGORY_ID, URL, COLSEQ) 
  VALUES ((SELECT ID FROM ALBUMCATEGORY WHERE NAME = '課室'), 'images/classroom2.jpg', 2);

INSERT INTO ALBUMIMAGE (CATEGORY_ID, URL, COLSEQ) 
  VALUES ((SELECT ID FROM ALBUMCATEGORY WHERE NAME = '課室'), 'images/classroom3.jpg', 3);

INSERT INTO ALBUMIMAGE (CATEGORY_ID, URL, COLSEQ) 
  VALUES ((SELECT ID FROM ALBUMCATEGORY WHERE NAME = '課室'), 'images/classroom4.jpg', 4);

INSERT INTO ALBUMIMAGE (CATEGORY_ID, URL, COLSEQ) 
  VALUES ((SELECT ID FROM ALBUMCATEGORY WHERE NAME = '課室'), 'images/classroom5.jpg', 5);

INSERT INTO ALBUMIMAGE (CATEGORY_ID, URL, COLSEQ) 
  VALUES ((SELECT ID FROM ALBUMCATEGORY WHERE NAME = '課室'), 'images/classroom6.jpg', 6);

INSERT INTO ALBUMIMAGE (CATEGORY_ID, URL, COLSEQ) 
  VALUES ((SELECT ID FROM ALBUMCATEGORY WHERE NAME = '庭院'), 'images/courtyard1.jpg', 1);

INSERT INTO ALBUMIMAGE (CATEGORY_ID, URL, COLSEQ) 
  VALUES ((SELECT ID FROM ALBUMCATEGORY WHERE NAME = '庭院'), 'images/courtyard2.jpg', 2);

INSERT INTO ALBUMIMAGE (CATEGORY_ID, URL, COLSEQ) 
  VALUES ((SELECT ID FROM ALBUMCATEGORY WHERE NAME = '庭院'), 'images/courtyard3.jpg', 3);

INSERT INTO ALBUMIMAGE (CATEGORY_ID, URL, COLSEQ) 
  VALUES ((SELECT ID FROM ALBUMCATEGORY WHERE NAME = '庭院'), 'images/courtyard4.jpg', 4);

INSERT INTO ALBUMIMAGE (CATEGORY_ID, URL, COLSEQ) 
  VALUES ((SELECT ID FROM ALBUMCATEGORY WHERE NAME = '庭院'), 'images/courtyard5.jpg', 5);

INSERT INTO ALBUMIMAGE (CATEGORY_ID, URL, COLSEQ) 
  VALUES ((SELECT ID FROM ALBUMCATEGORY WHERE NAME = '庭院'), 'images/courtyard6.jpg', 6);

INSERT INTO ALBUMIMAGE (CATEGORY_ID, URL, COLSEQ) 
  VALUES ((SELECT ID FROM ALBUMCATEGORY WHERE NAME = '庭院'), 'images/courtyard7.jpg', 7);

INSERT INTO ALBUMIMAGE (CATEGORY_ID, URL, COLSEQ) 
  VALUES ((SELECT ID FROM ALBUMCATEGORY WHERE NAME = '庭院'), 'images/courtyard8.jpg', 8);

INSERT INTO ALBUMIMAGE (CATEGORY_ID, URL, COLSEQ) 
  VALUES ((SELECT ID FROM ALBUMCATEGORY WHERE NAME = '舊翼'), 'images/oldwing1.jpg', 1);

INSERT INTO ALBUMIMAGE (CATEGORY_ID, URL, COLSEQ) 
  VALUES ((SELECT ID FROM ALBUMCATEGORY WHERE NAME = '舊翼'), 'images/oldwing2.jpg', 2);

INSERT INTO ALBUMIMAGE (CATEGORY_ID, URL, COLSEQ) 
  VALUES ((SELECT ID FROM ALBUMCATEGORY WHERE NAME = '舊翼'), 'images/oldwing3.jpg', 3);

INSERT INTO ALBUMIMAGE (CATEGORY_ID, URL, COLSEQ) 
  VALUES ((SELECT ID FROM ALBUMCATEGORY WHERE NAME = '舊翼'), 'images/oldwing4.jpg', 4);

INSERT INTO ALBUMIMAGE (CATEGORY_ID, URL, COLSEQ) 
  VALUES ((SELECT ID FROM ALBUMCATEGORY WHERE NAME = '舊翼'), 'images/oldwing5.jpg', 5);

INSERT INTO ALBUMIMAGE (CATEGORY_ID, URL, COLSEQ) 
  VALUES ((SELECT ID FROM ALBUMCATEGORY WHERE NAME = '舊翼'), 'images/oldwing7.jpg', 6);

INSERT INTO ALBUMIMAGE (CATEGORY_ID, URL, COLSEQ) 
  VALUES ((SELECT ID FROM ALBUMCATEGORY WHERE NAME = '舊翼'), 'images/oldwing9.jpg', 7);

INSERT INTO ALBUMIMAGE (CATEGORY_ID, URL, COLSEQ) 
  VALUES ((SELECT ID FROM ALBUMCATEGORY WHERE NAME = '舊翼'), 'images/oldwing10.jpg', 8);

INSERT INTO ALBUMIMAGE (CATEGORY_ID, URL, COLSEQ) 
  VALUES ((SELECT ID FROM ALBUMCATEGORY WHERE NAME = '舊翼'), 'images/oldwing11.jpg', 9);

INSERT INTO ALBUMIMAGE (CATEGORY_ID, URL, COLSEQ) 
  VALUES ((SELECT ID FROM ALBUMCATEGORY WHERE NAME = '舊翼'), 'images/oldwing12.jpg', 10);

INSERT INTO ALBUMIMAGE (CATEGORY_ID, URL, COLSEQ) VALUES (
	(SELECT ID FROM ALBUMCATEGORY WHERE NAME = '修道院'), 'images/conventbldg1.jpg', 1);
INSERT INTO ALBUMIMAGE (CATEGORY_ID, URL, COLSEQ) VALUES (
	(SELECT ID FROM ALBUMCATEGORY WHERE NAME = '修道院'), 'images/conventbldg2.jpg', 2);
INSERT INTO ALBUMIMAGE (CATEGORY_ID, URL, COLSEQ) VALUES (
	(SELECT ID FROM ALBUMCATEGORY WHERE NAME = '修道院'), 'images/conventbldg3.jpg', 3);
INSERT INTO ALBUMIMAGE (CATEGORY_ID, URL, COLSEQ) VALUES (
	(SELECT ID FROM ALBUMCATEGORY WHERE NAME = '修道院'), 'images/conventbldg4.jpg', 4);

INSERT INTO ALBUMIMAGE (CATEGORY_ID, URL, COLSEQ) VALUES (
	(SELECT ID FROM ALBUMCATEGORY WHERE NAME = '修道院'), 'images/conventbldg5.jpg', 5);

INSERT INTO ALBUMIMAGE (CATEGORY_ID, URL, COLSEQ) VALUES (
	(SELECT ID FROM ALBUMCATEGORY WHERE NAME = '修道院'), 'images/conventbldg6.jpg', 6);

INSERT INTO ALBUMIMAGE (CATEGORY_ID, URL, COLSEQ) VALUES (
	(SELECT ID FROM ALBUMCATEGORY WHERE NAME = '體育設施'), 'images/basketballcourt1.jpg', 1);

INSERT INTO ALBUMIMAGE (CATEGORY_ID, URL, COLSEQ) VALUES (
	(SELECT ID FROM ALBUMCATEGORY WHERE NAME = '體育設施'), 'images/basketballcourt2.jpg', 2);

INSERT INTO ALBUMIMAGE (CATEGORY_ID, URL, COLSEQ) VALUES (
	(SELECT ID FROM ALBUMCATEGORY WHERE NAME = '體育設施'), 'images/basketballcourt3.jpg', 3);

INSERT INTO ALBUMIMAGE (CATEGORY_ID, URL, COLSEQ) VALUES (
	(SELECT ID FROM ALBUMCATEGORY WHERE NAME = '體育設施'), 'images/playground1.jpg', 4);

INSERT INTO ALBUMIMAGE (CATEGORY_ID, URL, COLSEQ) VALUES (
	(SELECT ID FROM ALBUMCATEGORY WHERE NAME = '體育設施'), 'images/playground2.jpg', 5);

INSERT INTO ALBUMIMAGE (CATEGORY_ID, URL, COLSEQ) VALUES (
	(SELECT ID FROM ALBUMCATEGORY WHERE NAME = '體育設施'), 'images/playground3.jpg', 6);

INSERT INTO ALBUMIMAGE (CATEGORY_ID, URL, COLSEQ) VALUES (
	(SELECT ID FROM ALBUMCATEGORY WHERE NAME = '體育設施'), 'images/pool1.jpg', 7);

INSERT INTO ALBUMIMAGE (CATEGORY_ID, URL, COLSEQ) VALUES (
	(SELECT ID FROM ALBUMCATEGORY WHERE NAME = '體育設施'), 'images/pool2.jpg', 8);

INSERT INTO ALBUMIMAGE (CATEGORY_ID, URL, COLSEQ) 
  VALUES ((SELECT ID FROM ALBUMCATEGORY WHERE NAME = '美術室'), 'images/artroom5.jpg', 5);

SELECT A.NAME, B.URL
FROM ALBUMCATEGORY A
JOIN ALBUMIMAGE  B ON A.ID = B.CATEGORY_ID
ORDER BY A.COLSEQ, B.COLSEQ
